# Generated by Django 5.1.3 on 2024-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=24)),
                ('ctype', models.CharField(choices=[('url', 'URL'), ('txt', 'Text'), ('pic', 'Picture')], max_length=3)),
                ('url', models.URLField(blank=True, max_length=192, null=True)),
                ('btime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
