# Generated by Django 5.1.2 on 2024-11-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=24)),
                ('ctype', models.CharField(choices=[('url', 'URL'), ('txt', 'Text'), ('pic', 'Picture'), ('xyz', 'Mock type, DNE')], max_length=3)),
                ('btime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.item')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
