# Generated by Django 5.1.2 on 2024-11-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.item')),
                ('url', models.URLField(max_length=255)),
            ],
            bases=('core.item',),
        ),
    ]
