# Generated by Django 5.1.3 on 2025-01-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicItem',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.item')),
                ('format', models.CharField(choices=[('jpg', 'JPEG'), ('gif', 'GIF'), ('png', 'PNG')], max_length=4)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
