#!/usr/bin/env python
# scripts/generate-conformance-vectors.py
"""
Emit the shared conformance vector file for the blake3 + Crockford scheme.

Holds every hand-derived value as a literal, asserts depo's implementation
reproduces each one, then writes JSON to stdout or an optional path. The
literals are deliberately a second copy of the test module's constants: the
two must agree, and this script is what catches drift between them.

Author: Marcus Grant
Date: 2026-07-23
License: Apache-2.0
"""

import argparse
import json
import sys
from pathlib import Path

from depo.util.shortcode import _encode_crockford_b32, _hash_digest

BLAKE3_VECTORS = Path("tests/vectors/blake3-1.8.5-93a431c.json")

SCHEME_COMMENT = (
    "Unkeyed BLAKE3 sliced to 120 bits, encoded low-pad bitstream Crockford "
    "Base32 over the alphabet 0123456789ABCDEFGHJKMNPQRSTVWXYZ. Inputs are raw "
    "bytes. A case gives its input as input_hex, or as input_len for inputs "
    "generated by the rule byte i is i mod 251. The encoded field is the "
    "Crockford encoding of the input bytes themselves. The digest field is the "
    "120-bit BLAKE3 digest as hex and digest_encoded is its Crockford encoding. "
    "Fields are present only where the value was derived."
)

# Encoder vectors: input bytes to their Crockford encoding.
# Hand-derived and confirmed against independent codecs.
ENCODE_VECTORS = [
    (b"", ""),
    (b"\x00", "00"),
    (b"\x1f", "3W"),
    (b"\xff", "ZW"),
    (b"\x00\x01", "000G"),
    (b"\x84\x21", "GGGG"),
    (b"\x00" * 5, "00000000"),
    (b"\xff" * 5, "ZZZZZZZZ"),
    (b"\xaa" * 3, "NANAM"),
    (b"f", "CR"),
    (b"fo", "CSQG"),
    (b"foo", "CSQPY"),
    (b"foob", "CSQPYRG"),
    (b"fooba", "CSQPYRK1"),
    (b"foobar", "CSQPYRK1E8"),
    (b"test", "EHJQ6X0"),
]

# Periodic vectors at lengths 10 to 14, covering all five pad residues.
PERIODIC_VECTORS = [
    (b"\xaa" * 10, "NANANANANANANANA"),
    (b"\xaa" * 11, "NANANANANANANANAN8"),
    (b"\xaa" * 12, "NANANANANANANANANAN0"),
    (b"\xaa" * 13, "NANANANANANANANANANAM"),
    (b"\xaa" * 14, "NANANANANANANANANANANAG"),
    (b"\xff" * 10, "Z" * 16),
    (b"\xff" * 11, ("Z" * 17) + "W"),
    (b"\xff" * 12, ("Z" * 19) + "G"),
    (b"\xff" * 13, ("Z" * 20) + "Y"),
    (b"\xff" * 14, ("Z" * 22) + "R"),
    (b"\x00" * 10, "0" * 16),
    (b"\x00" * 11, "0" * 18),
    (b"\x00" * 12, "0" * 20),
    (b"\x00" * 13, "0" * 21),
    (b"\x00" * 14, "0" * 23),
]

# Full pipeline over reference inputs, keyed by length.
# Derived from the pinned BLAKE3 reference hex through the certified encoder.
REFERENCE_VECTORS = [
    (0, "NW9MKEFNZ6GTD8209QN3DQ69"),
    (1023, "2088JW7EV8ZBJCNTNGA2HHX2"),
    (1024, "88GMEEFGJPJ0DWZWGFFBH2BM"),
    (1025, "T017HBJ7XCKV6KXESXKV9ZH6"),
    (2049, "BX6Q5X0DF9FR5CAWMASE8JRX"),
]

# Full pipeline over literal inputs. Derived by this implementation only:
# they detect change, not error.
CONVENIENCE_VECTORS = [
    (b"Hello, World!\n", "C8SR6JYEF0BXP7J03F7EMAWB"),
    (b"\x00\xff\r\n\x1a", "56V71DGBAMEA57K94KP1NKF8"),
    (b"\xe2\x9c\x85", "2A9V46HDZYE86ESAZ71PZ8Y6"),
]


def reference_input(input_len: int) -> bytes:
    """Reconstruct a reference input: byte i is i mod 251."""
    return bytes(i % 251 for i in range(input_len))


def check(label: str, actual: str, expect: str) -> None:
    """Fail loud if the implementation disagrees with a held literal."""
    if actual != expect:
        sys.exit(f"{label}: implementation gave {actual!r}, literal says {expect!r}")


def build_cases() -> list[dict]:
    """Assert every literal against the implementation, then build the cases."""
    cases: list[dict] = []

    for data, expect in ENCODE_VECTORS + PERIODIC_VECTORS:
        check(f"encode {data!r}", _encode_crockford_b32(data), expect)
        cases.append({"input_hex": data.hex(), "encoded": expect})

    digests = {
        c["input_len"]: c["hash"]
        for c in json.loads(BLAKE3_VECTORS.read_text(encoding="utf-8"))["cases"]
    }
    for input_len, expect in REFERENCE_VECTORS:
        data = reference_input(input_len)
        digest = _hash_digest(data)
        check(f"digest len {input_len}", digest.hex(), digests[input_len][:30])
        check(f"pipeline len {input_len}", _encode_crockford_b32(digest), expect)
        cases.append(
            {
                "input_len": input_len,
                "digest": digest.hex(),
                "digest_encoded": expect,
            }
        )

    for data, expect in CONVENIENCE_VECTORS:
        digest = _hash_digest(data)
        check(f"pipeline {data!r}", _encode_crockford_b32(digest), expect)
        cases.append(
            {
                "input_hex": data.hex(),
                "digest": digest.hex(),
                "digest_encoded": expect,
            }
        )

    return cases


def main() -> None:
    """Emit the vector file to stdout or an optional path."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, help="write here, else stdout")
    args = parser.parse_args()

    document = {"_comment": SCHEME_COMMENT, "cases": build_cases()}
    text = json.dumps(document, indent=2) + "\n"

    if args.output:
        args.output.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()